// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYl16Zjd6q0Vds0zyM6ifuUzj315x6CZ0',
    appId: '1:264564772185:web:481540791aa6484b23d048',
    messagingSenderId: '264564772185',
    projectId: 'fluttergetx-dff02',
    authDomain: 'fluttergetx-dff02.firebaseapp.com',
    storageBucket: 'fluttergetx-dff02.firebasestorage.app',
    measurementId: 'G-FMKHPRTJZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaaO32OJnOWBgYHz_fNxhpZBBb9jt8M0A',
    appId: '1:264564772185:android:73d493d2254d829823d048',
    messagingSenderId: '264564772185',
    projectId: 'fluttergetx-dff02',
    storageBucket: 'fluttergetx-dff02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCee4zEMyaiP6KA7I6uR66xMteitEPNdBY',
    appId: '1:264564772185:ios:27c03e238189f1e423d048',
    messagingSenderId: '264564772185',
    projectId: 'fluttergetx-dff02',
    storageBucket: 'fluttergetx-dff02.firebasestorage.app',
    iosBundleId: 'com.example.flutterGetxProject',
  );
}
